name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Registry
        env:
          DOCKER_REGISTRY_URL: https://registry.hub.docker.com/v2/
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${DOCKER_REGISTRY_URL}
      - name: Check Docker login status
        run: docker info
      - name: Clean Docker cache
        run: docker builder prune -f
      - name: Build Docker image
        run: docker build -t neutron13evd/twpo3:$GITHUB_SHA .
      - name: Push Docker image
        run: docker push neutron13evd/twpo3:$GITHUB_SHA
